pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }

  post {
        always {
            script {
                sh 'docker rmi -f maven:3.8.1-adoptopenjdk-11'
                sh 'docker rmi -f node:16-alpine'
            }
        }
  }
}
